[libraries]

std.files = ['std/*.vhd']
std.is_third_party = true

ieee.files = ['ieee/*.vhdl', 'synopsys/*.vhd', 'vital2000/*.vhdl', 'unifast/primitive/*.vhd', 'unifast/secureip/*.vhd', 'unimacro/*.vhd']
ieee.is_third_party = true
