name: Bug Report
description: Report a bug to us.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        "You give me a peach, I repay you with a jade."
        Please read [nc-ai | About Feedback](https://nc-ai.cn/article/cxnqr517/#%E5%85%B3%E4%BA%8E%E5%8F%8D%E9%A6%88) before filling out this form.
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you running on?
      options:
        - Windows
        - Mac
        - Linux
        - Other
      default: 0
    validations:
      required: true
  - type: dropdown
    id: chip
    attributes:
      label: Chip Architecture
      description: What chip architecture are you running on?
      options:
        - x86
        - arm
        - loongson
        - Other
      default: 0
    validations:
      required: true
  - type: dropdown
    id: connect
    attributes:
      label: Running Method
      description: How are you running the software?
      options:
        - Desktop
        - SSH Remote Connection
        - WSL2
        - Virtual Machine
        - Other
      default: 0
    validations:
      required: true
  - type: input
    id: vscode-version
    attributes:
      label: Vscode / Vscodium Version
      placeholder: "1.96.2"
    validations:
      required: true
  - type: input
    id: dide-version
    attributes:
      label: Digital IDE Version
      placeholder: "0.4.0"
    validations:
      required: true
  - type: textarea
    id: meet-question
    attributes:
      label: Issue You Encountered
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: Expected Result
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
    validations:
      required: false
  - type: textarea
    id: log
    attributes:
      label: Runtime Log
      render: shell
    validations:
      required: false
